src/Entity/Membres.php
<?php

namespace App\Entity;

use App\Repository\MembresRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: MembresRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class Membres implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    #[ORM\Column(type: 'string', length: 255)]
    private $prenom;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Specialite;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Phone;

    #[ORM\Column(type: 'string', length: 255)]
    private $Type;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $image;

    #[ORM\ManyToMany(targetEntity: ProjetRecherche::class, mappedBy: 'Membres')]
    private $projetRecherches;

    #[ORM\ManyToMany(targetEntity: Publication::class, mappedBy: 'membres')]
    private $membres;

    #[ORM\OneToMany(mappedBy: 'Auteur', targetEntity: Publication::class)]
    private $Auteur;

    #[ORM\ManyToMany(targetEntity: Equipe::class, mappedBy: 'Membres')]
    private $Mequipe;

    #[ORM\Column(type: 'text', nullable: true)]
    private $Introduction;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Etablissement;



    public function __construct()
    {
        $this->projetRecherches = new ArrayCollection();
        $this->publications = new ArrayCollection();
        $this->Auteur = new ArrayCollection();
        $this->membres = new ArrayCollection();
        $this->Mequipe = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getSpecialite(): ?string
    {
        return $this->Specialite;
    }

    public function setSpecialite(?string $Specialite): self
    {
        $this->Specialite = $Specialite;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->Phone;
    }

    public function setPhone(?string $Phone): self
    {
        $this->Phone = $Phone;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->Type;
    }

    public function setType(string $Type): self
    {
        $this->Type = $Type;

        return $this;
    }
    public function __toString(): string
    {
        // TODO: Implement __toString() method.
        return $this->getNom()." ".$this->getPrenom();
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection<int, ProjetRecherche>
     */
    public function getProjetRecherches(): Collection
    {
        return $this->projetRecherches;
    }

    public function addProjetRecherch(ProjetRecherche $projetRecherch): self
    {
        if (!$this->projetRecherches->contains($projetRecherch)) {
            $this->projetRecherches[] = $projetRecherch;
            $projetRecherch->addMembre($this);
        }

        return $this;
    }

    public function removeProjetRecherch(ProjetRecherche $projetRecherch): self
    {
        if ($this->projetRecherches->removeElement($projetRecherch)) {
            $projetRecherch->removeMembre($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Publication>
     */
    public function getMembres(): Collection
    {
        return $this->membres;
    }

    public function addMembre(Publication $membre): self
    {
        if (!$this->membres->contains($membre)) {
            $this->membres[] = $membre;
            $membre->addMembre($this);
        }

        return $this;
    }

    public function removeMembre(Publication $membre): self
    {
        if ($this->membres->removeElement($membre)) {
            $membre->removeMembre($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Publication>
     */
    public function getAuteur(): Collection
    {
        return $this->Auteur;
    }

    public function addAuteur(Publication $auteur): self
    {
        if (!$this->Auteur->contains($auteur)) {
            $this->Auteur[] = $auteur;
            $auteur->setAuteur($this);
        }

        return $this;
    }

    public function removeAuteur(Publication $auteur): self
    {
        if ($this->Auteur->removeElement($auteur)) {
            // set the owning side to null (unless already changed)
            if ($auteur->getAuteur() === $this) {
                $auteur->setAuteur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Equipe>
     */
    public function getMequipe(): Collection
    {
        return $this->Mequipe;
    }

    public function addMequipe(Equipe $mequipe): self
    {
        if (!$this->Mequipe->contains($mequipe)) {
            $this->Mequipe[] = $mequipe;
            $mequipe->addMembre($this);
        }

        return $this;
    }

    public function removeMequipe(Equipe $mequipe): self
    {
        if ($this->Mequipe->removeElement($mequipe)) {
            $mequipe->removeMembre($this);
        }

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->Introduction;
    }

    public function setIntroduction(?string $Introduction): self
    {
        $this->Introduction = $Introduction;

        return $this;
    }

    public function getEtablissement(): ?string
    {
        return $this->Etablissement;
    }

    public function setEtablissement(?string $Etablissement): self
    {
        $this->Etablissement = $Etablissement;

        return $this;
    }


}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\Membres;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class ProfileController extends AbstractController{
    #[Route(path: '/profile', name: 'app_Profile')]
    public function index(AuthenticationUtils $authenticationUtils): Response
    {
        $membre=$this->getUser()->getRoles();
         switch ($membre[0]){
             case 'ROLE_Admin':
                 return $this->redirectToRoute('app_admin');
                 break;
             case 'ROLE_Professeur':
                 return $this->redirectToRoute('app_prof');
                 break;
             case 'ROLE_Doctorant':
                 return $this->redirectToRoute('app_profdoct');
                 break;
             case 'ROLE_Master':
                 return $this->redirectToRoute('app_profM');
                 break;
             case 'ROLE_Stagiaire':
                 return $this->redirectToRoute('app_profSt');
                 break;
             case 'ROLE_PostDoc':
                 return $this->redirectToRoute('app_profPos');
                 break;}
        return $this->redirectToRoute('app_admin');}

}

templates/profile/ajouteST.html.twig
{% block section %}
    <head>
        <meta charset="utf-8">
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <title>Profile</title>
        <meta content="" name="description">
        <meta content="" name="keywords">
        <!--NAVBAR -->
        <!-- -->
        <!-- FORM-->
        <link rel="shortcut icon" href="{{ asset('assets/img/img1.jpg') }}">
        <link href="{{ asset('assets2/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
        <!-- -->

        <!--select2 -->
        <link href="{{ asset('node_modules/select2/dist/css/select2.min.css') }}" rel="stylesheet">
        <!-- -->

    </head>
    <div class="alert-secondary" >
        <div class="container " style="margin-top: -27px;margin-bottom:-60px; ">
            <a class="navbar-brand" href="{{ path('app_prof') }}">
                <img style="margin-top: 20px;margin-bottom: -48px;margin-left: -113px" src="{{ asset('assets/img/Logo-UIZ.jpg') }}" width="120" height="100" alt="">
            </a>
            <div class="main  alert-secondary" >
                <br>
                <h1 class="mt-4" style="padding-left: 300px;margin-top: 100px">AJOUTE SUJET DE THESE</h1>
                {{ form_start(form) }}
                {{ form_widget(form) }}

                <a href="">  <button type="submit" class="btn btn-primary btn-lg my-3">Envoyer</button></a>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
    <!--select2 -->
    <script src="{{ asset('assets/js/scripts.js') }}"></script>
    <script src="{{ asset('node_modules/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ asset('node_modules/select2/dist/js/select2.min.js') }}"></script>
    <!--select2 -->

{% endblock %}
{% block javascripts %}
    <script>
        $(document).ready(function() {
            $('.select2').select2();
        });
    </script>
{% endblock %}

templates/profile/ajouterPB.html.twig
{% block section %}
    <head>
        <meta charset="utf-8">
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <title>Profile</title>
        <meta content="" name="description">
        <meta content="" name="keywords">
        <!--NAVBAR -->
        <!-- -->
        <!-- FORM-->
        <link rel="shortcut icon" href="{{ asset('assets/img/img1.jpg') }}">
        <link href="{{ asset('assets2/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
        <!-- -->

        <!--select2 -->
        <link href="{{ asset('node_modules/select2/dist/css/select2.min.css') }}" rel="stylesheet">
        <!-- -->

    </head>
    <div class="alert-secondary" >
        <div class="container " style="margin-top: -27px;margin-bottom:-60px; ">
            <a class="navbar-brand" href="{{ path('app_prof') }}">
                <img style="margin-top: 20px;margin-bottom: -48px;margin-left: -113px" src="{{ asset('assets/img/Logo-UIZ.jpg') }}" width="120" height="100" alt="">
            </a>
            <div class="main  alert-secondary" >
                <br>
                <h1 class="mt-4" style="padding-left: 350px;margin-top: 100px">AJOUTE PUBLICATION</h1>
                {{ form_start(form) }}
                {{ form_widget(form) }}

                <a href="">  <button type="submit" class="btn btn-primary btn-lg my-3">Envoyer</button></a>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
<!--select2 -->
<script src="{{ asset('assets/js/scripts.js') }}"></script>
<script src="{{ asset('node_modules/jquery/dist/jquery.min.js') }}"></script>
<script src="{{ asset('node_modules/select2/dist/js/select2.min.js') }}"></script>
<!--select2 -->

{% endblock %}
{% block javascripts %}
    <script>
        $(document).ready(function() {
            $('.select2').select2();
        });
    </script>
{% endblock %}

templates/profile/ajouterPr.html.twig
{% block section %}
    <head>
        <meta charset="utf-8">
        <meta content="width=device-width, initial-scale=1.0" name="viewport">

        <title>Profile</title>
        <meta content="" name="description">
        <meta content="" name="keywords">
        <!-- FORM-->
        <link rel="shortcut icon" href="{{ asset('assets/img/img1.jpg') }}">
        <link href="{{ asset('assets2/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
        <!-- -->

        <!--select2 -->
        <link href="{{ asset('node_modules/select2/dist/css/select2.min.css') }}" rel="stylesheet">
        <!-- -->

       </head>
       <div class="alert-secondary" >
      <div class="container " style="margin-top: -27px;margin-bottom:-60px; ">
        <a class="navbar-brand" href="{{ path('app_prof') }}">
            <img style="margin-top: 20px;margin-bottom: -28px;margin-left: -113px" src="{{ asset('assets/img/Logo-UIZ.jpg') }}" width="120" height="100" alt="">
        </a>
      <div class="main  alert-secondary" >
        <br>
        <h1 class="mt-4" style="padding-left: 250px;margin-top: 100px">AJOUTE PROJET DE RECHERCHE</h1>
        {{ form_start(form) }}
        {{ form_widget(form) }}

        <a href="">  <button type="submit" class="btn btn-primary btn-lg my-3">Envoyer</button></a>
        {{ form_end(form) }}
    </div>
    </div>
    </div>

    <!--select2 -->
    <script src="{{ asset('assets/js/scripts.js') }}"></script>
    <script src="{{ asset('node_modules/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ asset('node_modules/select2/dist/js/select2.min.js') }}"></script>
    <!--select2 -->

{% endblock %}
{% block javascripts %}
    <script>
        $(document).ready(function() {
            $('.select2').select2();
        });
    </script>
    <script>
        $.fn.select2.defaults.set("pro", "classic");
    </script>
{% endblock %}

templates/profile/ajouterSR.html.twig
{% block section %}
    <head>
        <meta charset="utf-8">
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <title>Profile</title>
        <meta content="" name="description">
        <meta content="" name="keywords">
        <!--NAVBAR -->
        <!-- -->
        <!-- FORM-->
        <link rel="shortcut icon" href="{{ asset('assets/img/img1.jpg') }}">
        <link href="{{ asset('assets2/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
        <!-- -->

        <!--select2 -->
        <link href="{{ asset('node_modules/select2/dist/css/select2.min.css') }}" rel="stylesheet">
        <!-- -->
    </head>
    <div class="alert-secondary" >
        <div class="container " style="margin-top: -27px;margin-bottom:-60px; ">
            <a class="navbar-brand" href="{{ path('app_prof') }}">
                <img style="margin-top: 20px;margin-bottom: -48px;margin-left: -113px" src="{{ asset('assets/img/Logo-UIZ.jpg') }}" width="120" height="100" alt="">
            </a>
            <div class="main  alert-secondary" >
                <br>
                <h1 class="mt-4" style="padding-left: 280px;margin-top: 100px">AJOUTE SUJET DE RECHERCHE</h1>
                {{ form_start(form) }}
                {{ form_widget(form) }}

                <a href="">  <button type="submit" class="btn btn-primary btn-lg my-3">Envoyer</button></a>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
    <!--select2 -->
    <script src="{{ asset('assets/js/scripts.js') }}"></script>
    <script src="{{ asset('node_modules/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ asset('node_modules/select2/dist/js/select2.min.js') }}"></script>
    <!--select2 -->

{% endblock %}
{% block javascripts %}
    <script>
        $(document).ready(function() {
            $('.select2').select2();
        });
    </script>
{% endblock %}

templates/profile/editform.html.twig
{% block section %}
    <head>
        <meta charset="utf-8">
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <title>Profile</title>
        <meta content="" name="description">
        <meta content="" name="keywords">
        <!--NAVBAR -->
        <!-- -->
        <!-- FORM-->
        <link rel="shortcut icon" href="{{ asset('assets/img/img1.jpg') }}">
        <link href="{{ asset('assets2/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
        <!-- -->
    </head>
    <div class="alert-secondary" >
        <div class="container " style="margin-top: -27px;margin-bottom:-60px; ">
            <a class="navbar-brand" href="{{ path('app_prof') }}">
                <img style="margin-top: 20px; margin-bottom: -58px;margin-left: -113px" src="{{ asset('assets/img/Logo-UIZ.jpg') }}" width="120" height="100" alt="">
            </a>
            <div class="main  alert-secondary" >
                <br>
                <h1 class="mt-4" style="padding-left: 400px;margin-top: 100px">EDITE PROFILE</h1>
        {{ form_start(edit_form) }}
        {{ form_row(edit_form.nom) }}
        {{ form_row(edit_form.prenom) }}
        {{ form_row(edit_form.Specialite) }}
        {{ form_row(edit_form.Introduction) }}
        {{ form_row(edit_form.Etablissement) }}
        {{ form_row(edit_form.email) }}
        {{ form_row(edit_form.Phone) }}
        {{ form_row(edit_form.plainPassword, {
            label: 'Password'
        }) }}
        {{ form_row(edit_form.newPassword, {
            label: 'NewPassword'
        }) }}
        {{ form_row(edit_form.photo) }}
        {{ form_end(edit_form) }}


    </div>




{% endblock %}

templates/profile/postdoct.html.twig
<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PROFIL</title>
    <link href="profil/css/font-awesome/css/all.min.css?ver=1.2.1" rel="stylesheet">
    <link href="profil/css/mdb.min.css?ver=1.2.1" rel="stylesheet">
    <link href="profil/css/aos.css?ver=1.2.1" rel="stylesheet">
    <link href="profil/css/main.css?ver=1.2.1" rel="stylesheet">

    <!--drop down-->
    <script src="{{ asset('https://use.fontawesome.com/releases/v6.1.0/js/all.js') }}" crossorigin="anonymous"></script>
    <script src="{{ asset('assets/js/bootstrap.min.js') }}" crossorigin="anonymous"></script>
    <!---->
    <noscript>
        <style type="text/css">
            [data-aos] {
                opacity: 1 !important;
                transform: translate(0) scale(1) !important;
            }
        </style>
    </noscript>
</head>
<body class="bg-light" id="top">
{#<header class="d-print-none">
    <div class="container text-center text-lg-left">
        <div class="pt-2 clearfix">
            #}{#  <h1 class="site-title mb-0">Walter Patterson</h1>#}{#
            <a class="navbar-brand" href="{{ path('app_profPos') }}">
                <!--img src="{{ asset('assets/img/images.jpg') }}" width="80" height="80" alt=""-->
                <img style="margin-top: -12px;margin-bottom: -5px;margin-left: -115px" src="{{ asset('assets/img/Logo-UIZ.jpg') }}" width="120" height="100" alt="">
            </a>
            <div class="site-nav" style="margin-top: -80px;margin-right: -78px">
                <nav role="navigation">
                    <ul class="nav justify-content-center">
                        <li class="nav-item shadow-1"><a class="nav-link" href="#about" ><span class="menu-title">About</span></a>
                        </li>
                        <li class="nav-item shadow-1"><a class="nav-link" href="#PR"><span class="menu-title">Projet de Recherche </span></a>
                        </li>
                        <li class="nav-item shadow-1"><a class="nav-link" href="{{ path('edit_post',{id: app.user.id}) }}" ><span class="menu-title">EDIT PROFILE</span></a>
                        </li>
                        <li class="nav-item shadow-1"><a class="nav-link" href="{{ path('app_home') }}" ><span class="menu-title">HOME</span></a>
                        </li>
                        <li style="margin-top: -12px;margin-bottom: 15px" class="nav-item shadow-2-strong alert-secondary"><a class="nav-link" href="{{ path('app_login') }}" ><span class="menu-title">LOGOUT</span></a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>#}




<header class="header fixed-top " >
    <div class="branding">
        <div class="container-fluid">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top " id="mainNav">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="">
                    <!--img src="{{ asset('assets/img/images.jpg') }}" width="80" height="80" alt=""-->
                    <img style="margin-top: -11px;margin-bottom: -11px" src="{{ asset('assets/img/Logo-UIZ.jpg') }}" width="100" height="80" alt="">
                </a>
                <div class="container px-4 px-lg-5">
                    <a class="navbar-brand" href="">Profile</a>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent ">
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <ul class="navbar-nav ms-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    PROJET
                                </a>
                                <ul class="dropdown-menu " aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item " href="#PR">PROJET DE RECHERCHE</a></li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " aria-current="page" href="{{ path('edit_post',{id: app.user.id}) }}">EDIT PROFILE</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " aria-current="page" href="{{ path('app_home') }}">Home</a>
                            </li>
                            </li>
                            <li style="margin-top: -12px;margin-bottom: 15px" class="nav-item shadow-2-strong  alert-primary"><a class="nav-link" href="{{ path('app_login') }}" ><span class="menu-title text-dark">LOGOUT</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div><!--//container-->
    </div><!--//branding-->




</header>
<div class="page-content p" style="margin-top: 87px">
    <div class="container">
        <div class="resume-container">
            <div class="shadow-1-strong bg-white my-5" id="intro">
                <div class="bg-info text-white">
                    <div class="cover bg-image"><img src="profil/images/header-background.jpg"/>
                        <div class="mask" style="background-color: rgba(0,0,0,0.7);backdrop-filter: blur(2px);">
                            <div class="text-center p-5">
                                <div class="avatar p-1"><img class="img-thumbnail shadow-2-strong" src="uploads/membres/{{ app.user.image }}" width="160" height="160"/></div>
                                <div class="header-bio mt-3">
                                    <div data-aos="zoom-in" data-aos-delay="0">


                                        <h2 class="h1">{{ app.user.prenom }} {{ app.user.nom }}</h2>
                                        <p>{{ app.user.etablissement }}</p>


                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="shadow-2-strong bg-white my-5 p-5" id="about">
                <div class="about-section p-5">
                    <div class="row">
                        <div class="col-md-6 shadow-1">
                            <h2 class="h2 fw-light mb-4">Introduction</h2>
                            <hr>
                            {{ app.user.introduction }}
                        </div>

                        <div class="col-md-5 col offset-lg-1 shadow-1">
                            <div class="row mt-2">
                                <h2 class="h2 fw-light mb-4 ">Information</h2>
                                <hr>
                                <div class="col-sm-5">
                                    <div class="pb-2 fw-bolder"><i class="far pe-2 text-muted" style="width:24px;opacity:0.85;"></i> Nom</div>
                                </div>
                                <div class="col-sm-7">
                                    <div class="pb-2">        {{ app.user.nom }}</div>
                                </div>
                                <div class="col-sm-5">
                                    <div class="pb-2 fw-bolder"><i class="far  pe-2 text-muted" style="width:24px;opacity:0.85;"></i> Prenom</div>
                                </div>
                                <div class="col-sm-7">
                                    <div class="pb-2">        {{ app.user.prenom }}</div>
                                </div>
                                <div class="col-sm-5">
                                    <div class="pb-2 fw-bolder"><i class="fab pe-2 text-muted" style="width:24px;opacity:0.85;"></i> Specialite</div>
                                </div>
                                <div class="col-sm-7">
                                    <div class="pb-2">        {{ app.user.specialite }}</div>
                                </div>
                                <div class="col-sm-5">
                                    <div class="pb-2 fw-bolder"><i class="fas fa-envelope pe-2 text-muted" style="width:24px;opacity:0.85;"></i> Email</div>
                                </div>
                                <div class="col-sm-7">
                                    <div class="pb-2">       {{ app.user.email }}</div>
                                </div>
                                <div class="col-sm-5">
                                    <div class="pb-2 fw-bolder"><i class="fas fa-phone pe-2 text-muted" style="width:24px;opacity:0.85;"></i> Phone</div>
                                </div>
                                <div class="col-sm-7">
                                    <div class="pb-2">       {{ app.user.phone }}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div style="margin-bottom: 32px" Id="PR">
            <div class="row" >
                <div class="col-sm-12">
                    <div class="card-body">
                        <ul class="nav nav-tabs">
                            <li>
                                <a class="nav-link active text-uppercase " aria-selected="true">PROJET DE RECHERCHE</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>


            <div class="shadow-1-strong bg-white my-2 p-5">
                <div class="">
                    <div class="row">
                        <div class="col-md">

                            {% for pr in prech %}
                                <div class="timeline">
                                    <div class="timeline-card timeline-card-primary card shadow-sm">
                                        <div class="card-body">
                                            <div class="h5 mb-2">{{ pr.titre }}
                                                <br>
                                                <div class="mt-2">
                                                    <span class="text-muted h6">{{ pr.coordinateurPrinc }} &&</span>
                                                    <span class="text-muted  h6">
                                                       {% for l in pr.Membres %}
                                                           {{ l}} ,
                                                       {% endfor %}
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="text-muted text-small mb-2 "> à {{ pr.dateDebut | date("20y/m/d") }}  jusqu'a {{ pr.datefin | date("20y/m/d") }}   </div>
                                            <div>{{ pr.description}}</div>
                                            <span class="text-muted h6">{{ pr.coordinateurPrinc }} &&</span>

                                            <a   class=" bi-file-pdf" href="{{ asset("uploads/pdf/projetrecherche/")}}{{ s.pdf}}">
                                                <p class="icon-3d_rotation " >DOWNLOAD</p>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <hr>
                            {% endfor %}

                        </div>
                    </div>
                </div>
            </div>
        </div>

        <script src="{{ asset('assets2/vendor/aos/aos.js') }}"></script>
        <script src="assets2/vendor/glightbox/js/glightbox.min.js"></script>
        <script src="assets2/vendor/swiper/swiper-bundle.min.js"></script>
        <!-- Template Main JS File -->
        <script src="assets2/js/main.js"></script>
        <script src="profil/scripts/aos.js?ver=1.2.1"></script>
        <script src="profil/scripts/main.js?ver=1.2.1"></script>
    </div>
</div>
</div>






</body>
</html>