src/Entity/Equipe.php
<?php

namespace App\Entity;

use App\Repository\EquipeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EquipeRepository::class)]
class Equipe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    #[ORM\ManyToOne(targetEntity: Professeur::class, inversedBy: 'equipes')]
    #[ORM\JoinColumn(nullable: false)]
    private $chef;

    #[ORM\ManyToMany(targetEntity: Membres::class, inversedBy: 'Mequipe')]
    private $Membres;

    #[ORM\ManyToOne(targetEntity: Labo::class, inversedBy: 'equipes')]
    #[ORM\JoinColumn(nullable: true)]
    private $labo;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $domaine;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Specialites;

    public function __construct()
    {
        $this->Membres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getChef(): ?Professeur
    {
        return $this->chef;
    }

    public function setChef(?Professeur $chef): self
    {
        $this->chef = $chef;

        return $this;
    }

    /**
     * @return Collection<int, Membres>
     */
    public function getMembres(): Collection
    {
        return $this->Membres;
    }

    public function addMembre(Membres $membre): self
    {
        if (!$this->Membres->contains($membre)) {
            $this->Membres[] = $membre;
        }

        return $this;
    }

    public function removeMembre(Membres $membre): self
    {
        $this->Membres->removeElement($membre);

        return $this;
    }

    public function getLabo(): ?Labo
    {
        return $this->labo;
    }

    public function setLabo(?Labo $labo): self
    {
        $this->labo = $labo;

        return $this;
    }

    public function getDomaine(): ?string
    {
        return $this->domaine;
    }

    public function setDomaine(?string $domaine): self
    {
        $this->domaine = $domaine;

        return $this;
    }

    public function getSpecialites(): ?string
    {
        return $this->Specialites;
    }

    public function setSpecialites(?string $Specialites): self
    {
        $this->Specialites = $Specialites;

        return $this;
    }
}

src/Entity/Publication.php
<?php

namespace App\Entity;

use App\Repository\PublicationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PublicationRepository::class)]
class Publication
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $titre;

    #[ORM\Column(type: 'date')]
    private $annee;

    #[ORM\Column(type: 'string', length: 255)]
    private $lien;

    #[ORM\Column(type: 'text', nullable: true)]
    private $text;

    #[ORM\ManyToMany(targetEntity: Membres::class, inversedBy: 'membres')]
    private $membres;

    #[ORM\ManyToOne(targetEntity: Membres::class, inversedBy: 'Auteur')]
    private $Auteur;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Autre;


    public function __construct()
    {
        $this->membre = new ArrayCollection();
        $this->membres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getAnnee(): ?\DateTimeInterface
    {
        return $this->annee;
    }

    public function setAnnee(\DateTimeInterface $annee): self
    {
        $this->annee = $annee;

        return $this;
    }

    public function getLien(): ?string
    {
        return $this->lien;
    }

    public function setLien(string $lien): self
    {
        $this->lien = $lien;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(?string $text): self
    {
        $this->text = $text;

        return $this;
    }

    /**
     * @return Collection<int, Membres>
     */
    public function getMembres(): Collection
    {
        return $this->membres;
    }

    public function addMembre(Membres $membre): self
    {
        if (!$this->membres->contains($membre)) {
            $this->membres[] = $membre;
        }

        return $this;
    }

    public function removeMembre(Membres $membre): self
    {
        $this->membres->removeElement($membre);

        return $this;
    }

    public function getAuteur(): ?Membres
    {
        return $this->Auteur;
    }

    public function setAuteur(?Membres $Auteur): self
    {
        $this->Auteur = $Auteur;

        return $this;
    }

    public function getAutre(): ?string
    {
        return $this->Autre;
    }

    public function setAutre(?string $Autre): self
    {
        $this->Autre = $Autre;

        return $this;
    }


}

src/Controller/PubController.php
<?php

namespace App\Controller;

use App\Entity\Publication;
use App\Form\PublicationType;
use App\Repository\PublicationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PubController extends AbstractController
{
    #[Route('/pub', name: 'app_pub')]
    public function index(PublicationRepository $pubrepository): Response
    {
        $pub1=$pubrepository->findAll();
        return $this->render('pub/index.html.twig', [
            'p' => $pub1,
        ]);
    }

    #[Route('/publ', name: 'app_publ')]
    public function publ(Request $request,EntityManagerInterface $entityManager): Response
    {
        //  $us =$this->getUser()->getUserIdentifier();
        $pub = new Publication();
        $form = $this->createForm(PublicationType::class, $pub);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $pub = $form->getData();
            $entityManager->persist($pub);
            $entityManager->flush();
            //$sujetTheseRepository->add($suj);
        }
        return $this->render('pub/publ.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/pub1', name: 'app_pub1')]
    public function P_recherche(Request $request,PublicationRepository $pubrepository): Response
    {
        $t=$request->get('year');
        $d=strtotime($t);
        $td=getdate($d);
        $query=$pubrepository->createQueryBuilder('e')
            ->where('e.annee like :annee')
            ->setParameter('annee',$td['year'].'%')
            ->getQuery();
        $publist=$query->getResult();

        return $this->render(
            'pub/index.html.twig',
            array('p'=>$publist));
    }
}

templates/pub/index.html.twig
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Publication</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->





    <link href="assets1/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets1/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="assets1/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">



    <!-- Vendor CSS Files -->
    <link href="profil/css/font-awesome/css/all.min.css?ver=1.2.1" rel="stylesheet">
    <link href="profil/css/mdb.min.css?ver=1.2.1" rel="stylesheet">
    <link href="profil/css/aos.css?ver=1.2.1" rel="stylesheet">
    <link href="profil/css/main.css?ver=1.2.1" rel="stylesheet">
    <!-- Vendor CSS Files -->

    <!-- Template Main CSS File -->
    <link href="assets1/css/style.css" rel="stylesheet">


</head>

<body>

<!-- ======= Header ======= -->
<header id="header" class="fixed-top ">
    <div class="container  d-flex align-items-center">

        <h1 class="logo me-auto"><a href="#">Publication</a></h1>
        <nav id="navbar" class="navbar">
            <a class="navbar-brand " href="#">
                <img style="margin-left: -860px;margin-top: -19px" src="{{ asset('assets/img/Logo-UIZ.jpg') }}" width="120" height="80" alt="">
            </a>
            <ul>
            <form class="d-flex" method="post" action="{{ path('app_pub1') }}">
              <input class="form-control me-2" type="search"  placeholder="Search" aria-label="Search" name="year">
              <input type="submit" class="alert-success" value="Search">
            </form>
            </ul>


            <ul>
                <li><a class="nav-link scrollto active" href="{{ path('app_home') }}">Home</a></li>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>

        </nav><!-- .navbar -->

    </div>
</header><!-- End Header -->

<!-- ======= Frequently Asked Questions Section ======= -->
<section id="faq" class="faq section-bg">
    <div class=" container" data-aos="fade-up">

        {#  <div class="section-title">
            <h2  style="margin-left: -131px;margin-top: 22px">research for publish</h2>
         <p>
             On these pages you will find Springer’s journals, books and eBooks in all areas of Business and Management, serving researchers, professionals, lecturers and students. We publish many of the most prestigious journals in Business and Management, including a number of fully open access journals. Our book and eBook portfolio comprises major reference works, textbooks, and monographs from the world’s most distinguished authors. Well-known publications include: Springer Texts in Business and Economics, the Encyclopedia of Operations Research and Management Science, and the Journal of the Academy of Marketing Science.

         </p>#}
        </div>


        <div style="margin-bottom: 32px;margin-top: 40px" id="PR">
            <div class="row" >
                <div class="col-sm-12">
                    <div class="card-body">
                        <ul class="nav nav-tabs">
                            <li>
                                <a class="nav-link active text-uppercase " aria-selected="true">PUBLICATION</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class=" shadow-3-strong bg-white my-2 p-5">
                <div class="">
                    <div class="row">
                        <div class="col-md">
                            {% for pub in p%}
                                <div class="timeline">
                                    <div class="timeline-card timeline-card-primary card shadow-sm">
                                        <div class="card-body">
                                            <div class="h5 mb-2">{{ pub.titre}}
                                                <br>
                                                <div class="mt-2">
                                                    <span class="text-muted h6">{{ pub.auteur}} &&</span>
                                                    <span class="text-muted  h6">
                                                       {% for l in pub.membres %}
                                                           {{ l}} ,
                                                       {% endfor %}
                                                    </span>
                                                    <span class="text-muted  h6"> {{ pub.autre }}</span>
                                                </div>
                                            </div>
                                            <div class="text-muted text-small mb-2 "> {{ pub.annee | date("20y / m / d")}}  </div>
                                            <div>{{ pub.text}}</div>
                                            <hr>
                                            <span class="text-muted h6">
                                            <a href="{{ pub.lien }}">
                                             <p class=" icon-holder" >voir le journal --></p>
                                           </a>
                                        </span>
                                        </div>
                                    </div>
                                </div>
                                <hr>
                            {% endfor %}


                        </div>
                    </div>
                </div>
            </div>
        </div>


{#
{% for pub in p %}
        <div class="faq-list">
            <ul>
                <li data-aos="fade-up" data-aos-delay="100">
                 <a data-bs-toggle="collapse" class="collapse" data-bs-target="#faq-list-1">{{ pub.titre }}<i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
                    <div id="faq-list-1" class="collapse show" data-bs-parent=".faq-list">
                         <span class="text-muted  h6">
                                                       {% for l in pub.membres %}
                                                           {{ l}} ,
                                                       {% endfor %}
                                                    </span><br>
                            {{ pub.annee|date('Y/M/D')}}<hr>
                              {{ pub.text }}
                             <hr>
                        <a href="{{ pub.lien }}">
                            <p class=" icon-holder" >voir le journal --></p>
                        </a>
                    </div>
                </li>

            </ul>
        </div>
{% endfor %}
#}

    </div>
</section><!-- End Frequently Asked Questions Section -->
<!-- Vendor JS Files -->
<script src="assets1/vendor/aos/aos.js"></script>
<script src="assets1/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>




<!-- Template Main JS File -->
<script src="assets1/js/main.js"></script>

</body>

</html>

templates/pub/publ.html.twig
{% extends 'base.html.twig' %}

{% block title %}Registration Info{% endblock %}

{% block body %}
    <div class="main  bg-primary" style="padding: 60px;margin:0px;margin-top:-117px; margin-bottom: -117px">

        <h1 class="mt-4">Registration Info</h1>
        {{ form_start(form) }}
        {{ form_widget(form) }}

        <button type="submit" class="btn btn-secondary btn-lg my-3">Envoyer</button>
        {{ form_end(form) }}
    </div>
{% endblock %}