src/Entity/SujetRecherche.php
<?php

namespace App\Entity;

use App\Repository\SujetRechercheRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SujetRechercheRepository::class)]
class SujetRecherche
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $titre;

    #[ORM\Column(type: 'text', nullable: true)]
    private $description;

    #[ORM\ManyToOne(targetEntity: Master::class)]
    private $master;

    #[ORM\ManyToOne(targetEntity: Stagiaire::class)]
    private $Stagiaire;

    #[ORM\Column(type: 'boolean')]
    private $pfe;

    #[ORM\Column(type: 'date')]
    private $datedebut;

    #[ORM\Column(type: 'date')]
    private $datefine;

    #[ORM\OneToOne(inversedBy: 'sujetRecherche', targetEntity: ProjetRecherche::class, cascade: ['persist', 'remove'])]
    private $PrAssocie;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $pdf;

    #[ORM\ManyToOne(targetEntity: Professeur::class, inversedBy: 'sujetRecherches')]
    #[ORM\JoinColumn(nullable: false)]
    private $Encadren;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getMaster(): ?Master
    {
        return $this->master;
    }

    public function setMaster(?Master $master): self
    {
        $this->master = $master;

        return $this;
    }

    public function getStagiaire(): ?Stagiaire
    {
        return $this->Stagiaire;
    }

    public function setStagiaire(?Stagiaire $Stagiaire): self
    {
        $this->Stagiaire = $Stagiaire;

        return $this;
    }

    public function getPfe(): ?bool
    {
        return $this->pfe;
    }

    public function setPfe(bool $pfe): self
    {
        $this->pfe = $pfe;

        return $this;
    }

    public function getDatedebut(): ?\DateTimeInterface
    {
        return $this->datedebut;
    }

    public function setDatedebut(\DateTimeInterface $datedebut): self
    {
        $this->datedebut = $datedebut;

        return $this;
    }

    public function getDatefine(): ?\DateTimeInterface
    {
        return $this->datefine;
    }

    public function setDatefine(\DateTimeInterface $datefine): self
    {
        $this->datefine = $datefine;

        return $this;
    }

    public function getPrAssocie(): ?ProjetRecherche
    {
        return $this->PrAssocie;
    }

    public function setPrAssocie(?ProjetRecherche $PrAssocie): self
    {
        $this->PrAssocie = $PrAssocie;

        return $this;
    }

    public function getPdf(): ?string
    {
        return $this->pdf;
    }

    public function setPdf(?string $pdf): self
    {
        $this->pdf = $pdf;

        return $this;
    }

    public function getEncadren(): ?Professeur
    {
        return $this->Encadren;
    }

    public function setEncadren(?Professeur $Encadren): self
    {
        $this->Encadren = $Encadren;

        return $this;
    }
}

src/Entity/SujetThese.php
<?php

namespace App\Entity;

use App\Repository\SujetTheseRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SujetTheseRepository::class)]
class SujetThese
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $titre;

    #[ORM\Column(type: 'text')]
    private $description;

    #[ORM\Column(type: 'date')]
    private $annee;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $bourse;

    #[ORM\OneToOne(inversedBy: 'sujetThese', targetEntity: Doctorant::class, cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private $doctorant;

    #[ORM\ManyToOne(targetEntity: Professeur::class, inversedBy: 'sujetTheses')]
    #[ORM\JoinColumn(nullable: false)]
    private $encadrant;

    #[ORM\ManyToOne(targetEntity: Professeur::class)]
    private $coencadrant;

    #[ORM\OneToOne(inversedBy: 'sujetThese', targetEntity: ProjetRecherche::class, cascade: ['persist', 'remove'])]
    private $PrAssocie;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $pdf;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAnnee(): ?\DateTimeInterface
    {
        return $this->annee;
    }

    public function setAnnee(\DateTimeInterface $annee): self
    {
        $this->annee = $annee;

        return $this;
    }

    public function getBourse(): ?string
    {
        return $this->bourse;
    }

    public function setBourse(?string $bourse): self
    {
        $this->bourse = $bourse;

        return $this;
    }

    public function getDoctorant(): ?Doctorant
    {
        return $this->doctorant;
    }

    public function setDoctorant(Doctorant $doctorant): self
    {
        $this->doctorant = $doctorant;

        return $this;
    }

    public function getEncadrant(): ?Professeur
    {
        return $this->encadrant;
    }

    public function setEncadrant(?Professeur $encadrant): self
    {
        $this->encadrant = $encadrant;

        return $this;
    }

    public function getCoencadrant(): ?Professeur
    {
        return $this->coencadrant;
    }

    public function setCoencadrant(?Professeur $coencadrant): self
    {
        $this->coencadrant = $coencadrant;

        return $this;
    }

    public function getPrAssocie(): ?ProjetRecherche
    {
        return $this->PrAssocie;
    }

    public function setPrAssocie(?ProjetRecherche $PrAssocie): self
    {
        $this->PrAssocie = $PrAssocie;

        return $this;
    }

    public function getPdf(): ?string
    {
        return $this->pdf;
    }

    public function setPdf(?string $pdf): self
    {
        $this->pdf = $pdf;

        return $this;
    }
}

src/Form/ProjetType.php
<?php

namespace App\Form;

use App\Entity\Membres;
use App\Entity\Professeur;
use App\Entity\ProjetRecherche;
use App\Entity\SujetRecherche;
use App\Entity\SujetThese;
use Doctrine\DBAL\Types\DateType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Date;
use Symfony\Component\Validator\Constraints\File;

class ProjetType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('description')
            ->add('financement')
            ->add('dateDebut')
            ->add('Datefin', \Symfony\Component\Form\Extension\Core\Type\DateType::class,[
                'label' => 'date Fin',
                'attr' => [
                    'class'=>'mt-4'
                ]
            ])
            ->add('coordinateurPrinc' ,EntityType::class,[
                'label' => 'Coordinateur Principale',
                'expanded'=>false,
                'required'=>false,
                'class'=>Professeur::class,
                'multiple'=>false,
                'attr' => [
                    'class'=>'select2',
                ],
            ])
            ->add('sujetThese',EntityType::class,[
                'label' => 'Sujet de These',
                'expanded'=>false,
                'required'=>false,
                'class'=>SujetThese::class,
                'choice_label'=>'titre',
                'attr' => [
                    'class'=>'select2',
                ],
            ])
            ->add('sujetRecherche',EntityType::class,[
                    'label' => 'Sujet de Recherche',
                'expanded'=>false,
                'required'=>false,
                'class'=>SujetRecherche::class,
                'choice_label'=>'titre',
                'attr' => [
                        'class'=>'select2',
                    ],
                ]
            )
            ->add('Membres',EntityType::class,[
                'label' => 'Les Membres',
                'expanded'=>false,
                'required'=>false,
                'class'=>Membres::class,
                'multiple'=>true,
                'attr' => [
                    'class'=>'select2',
                ],
            ] )
            ->add('PDF', FileType::class, [
                'label' => 'PDF document',

                // unmapped means that this field is not associated to any entity property
                'mapped' => false,

                // make it optional so you don't have to re-upload the PDF file
                // every time you edit the Product details
                'required' => false,

                // unmapped fields can't define their validation using annotations
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'application/pdf',
                            'application/x-pdf',
                        ],
                        'mimeTypesMessage' => 'PDF document',
                    ])
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ProjetRecherche::class,
        ]);
    }
}

src/Controller/ProjetController.php
<?php

namespace App\Controller;

use App\Repository\ProjetRechercheRepository;
use App\Repository\SujetRechercheRepository;
use App\Repository\SujetTheseRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProjetController extends AbstractController
{
    #[Route('/prech', name: 'app_prech')]
    public function prech(ProjetRechercheRepository$repository ): Response
    {
        $prech =$repository->findAll();
        return $this->render('projet/prech.html.twig', [
            'prech' => $prech,
        ]);
    }


    #[Route('/1prech', name: 'app_prech1')]
    public function precheche(Request $request,ProjetRechercheRepository $repository ): Response
    {
        $t=$request->get('year');
        $d=strtotime($t);
        $td=getdate($d);
             $query=$repository->createQueryBuilder('e')
            ->where('e.dateDebut like :dateDebut')
            ->setParameter('dateDebut',$td['year'].'%')
            ->getQuery();
        $prlist=$query->getResult();
        return $this->render('projet/prech.html.twig',array('prech'=>$prlist));
             
    }



	
    #[Route('/sujrech', name: 'app_sujrech')]
    public function sujrech(SujetRechercheRepository $sujetRechercheRepository): Response
    {
        $sujrech=$sujetRechercheRepository->findAll();
        return $this->render('projet/sujrech.html.twig', [
            'sujrech' => $sujrech,
        ]);
    }


    #[Route('/sujdrech', name: 'app_sujrech1')]
    public function sujrecherch(Request $request,SujetRechercheRepository $sujetRechercheRepository): Response
    { 
        $t=$request->get('year');
        $d=strtotime($t);
        $td=getdate($d);
             $query=$sujetRechercheRepository->createQueryBuilder('e')
            ->where('e.datedebut like :datedebut')
            ->setParameter('datedebut',$td['year'].'%')
            ->getQuery();
	    $srlist=$query->getResult();
        return $this->render('projet/sujrech.html.twig',array('sujrech'=>$srlist));
    }



    #[Route('/sujthese', name: 'app_sujthese')]
    public function sujthese(SujetTheseRepository $sujetTRepository ): Response
    {
        $sujthese=$sujetTRepository->findAll();
        return $this->render('projet/sujthese.html.twig', [
            'sujthese' => $sujthese,
        ]);
    }




    #[Route('/sujdthese', name: 'app_sujthese1')]
    public function sujtheserecherche(Request $request,SujetTheseRepository $sujetTRepository ): Response
    {
             $t=$request->get('year');
             $d=strtotime($t);
             $td=getdate($d);
             $query=$sujetTRepository->createQueryBuilder('e')
            ->where('e.annee like :annee')
            ->setParameter('annee',$td['year'].'%')
            ->getQuery();
	    $stlist=$query->getResult();
        return $this->render('projet/sujthese.html.twig',array('sujthese' =>$stlist));
    }





    #[Route('/Result', name: 'liste_Projet_Recherche')]
    public function Recherche(Request $request,  ProjetRechercheRepository $prjRepository)
    {
        // $Request = $this->getRequest();
        $motcle = $request->get('motcle');
        $prech= $prjRepository->findBy(array('titre' => $motcle));
        //$entities  = $this->get('knp_paginator')->paginate(
        //  $Membres,
        // $request->query->get('page', 1)/*page number*/,
        // 6/*limit per page*/
        //);

        return $this->render('projet/prech.html.twig', [
            'prech' => $prech,
        ]);
    }
}

templates/projet/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProjetController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'D:/symfony7/ifdPFE_app/src/Controller/ProjetController.php'|file_link(0) }}">src/Controller/ProjetController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'D:/symfony7/ifdPFE_app/templates/projet/index.html.twig'|file_link(0) }}">templates/projet/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/projet/prech.html.twig
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>PROJET DE RECHERCHE</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->

    <link href="assets1/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets1/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="assets1/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">


    <!-- affichage projet de recherche  -->

    <link href="profil/css/mdb.min.css?ver=1.2.1" rel="stylesheet">
    <link href="profil/css/main.css?ver=1.2.1" rel="stylesheet">

    <!-- Template Main CSS File -->


    <!-- Template Main CSS File -->
    <link href="assets1/css/style.css" rel="stylesheet">


</head>

<body>

<!-- ======= Header ======= -->
<header  id="header" class="fixed-top ">
    <div class="container  d-flex align-items-center">

        <h1 class="logo me-auto"><a href="#faq">PROJET DE RECHERCHE</a></h1>
        <nav id="navbar" class="navbar">
            <ul >
                <form class="d-flex" method="post" action="{{ path('app_prech1') }}">
                    <input class="form-control me-2" type="search"  placeholder="Search" aria-label="Search" name="year">
                    <input type="submit" class="alert-success" value="Search">
                </form>
            </ul>
            <ul>
                <li><a class="nav-link scrollto active" href="{{ path('app_home') }}">Home</a></li>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->

    </div>
</header><!-- End Header -->

<!-- ======= Frequently Asked Questions Section ======= -->
<section id="faq" class="faq section-bg">
    <div class="container " data-aos="fade-up">

{#        <div class="section-title">
            <h2>about page</h2>
            <p>
                On these pages you will find Springer’s journals, books and eBooks in all areas of Business and Management, serving researchers, professionals, lecturers and students. We publish many of the most prestigious journals in Business and Management, including a number of fully open access journals. Our book and eBook portfolio comprises major reference works, textbooks, and monographs from the world’s most distinguished authors. Well-known publications include: Springer Texts in Business and Economics, the Encyclopedia of Operations Research and Management Science, and the Journal of the Academy of Marketing Science.
            </p>
        </div>#}

{#
{% for pr in prech %}
        <div class="faq-list">
            <ul>
                <li data-aos="fade-up" data-aos-delay="100">
                    <a data-bs-toggle="collapse" class="collapse" data-bs-target="#faq-list-1">{{ pr.titre }}<i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
                    <div id="faq-list-1" class="collapse show" data-bs-parent=".faq-list">
                            <h5 class="validate">debut projet:{{ pr.dateDebut |date('y/m/d     h:m') }}</h5>
                            <h5>fin projet:{{ pr.datefin|date('y/m/d     h:m') }}</h5>
                        <p>
                            {% for l in pr.Membres %}
                                {{ l}},

                            {% endfor %}

                            <hr>
                        {{ pr.description }}
                        </p><hr>
                        <a class="bi-file-pdf" href="{{ asset("uploads/pdf/projetrecherche/")}}{{ pr.pdf}}">
                            <p class=" icon-holder" >voir le journal --></p>
                        </a>

                    </div>
                </li>
            </ul>
        </div>
{% endfor %}#}

        <div style="margin-top: 80px;margin-bottom: 32px" id="PR">
            <div class="row" >
                <div class="col-sm-12">
                    <div class="card-body">
                        <ul class="nav nav-tabs">
                            <li>
                                <a class="nav-link active text-uppercase " aria-selected="true">PROJET DE RECHERCHE</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>


            <div class="shadow-2-strong bg-white my-2 p-5 mb-">
                <div class="">
                    <div class="row">
                        <div class="col-md-12">
                            {% for pr in prech %}
                                <div class="timeline">
                                    <div class="timeline-card timeline-card-primary card shadow-sm">
                                        <div class="card-body">
                                            <div class="h5 mb-2">{{ pr.titre }}
                                                <br>
                                                <div class="mt-2">
                                                    <span class="text-muted h6">{{ pr.coordinateurPrinc }} &&</span>
                                                    <span class="text-muted  h6">
                                                       {% for l in pr.Membres %}
                                                           {{ l}} ,
                                                       {% endfor %}
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="text-muted text-small mb-2 "> à {{ pr.dateDebut | date("20y/m/d") }}  jusqu'a {{ pr.datefin | date("20y/m/d") }}   </div>
                                            <div>{{ pr.description}}</div>
                                            <br>

                                            <a   class=" bi-file-pdf" href="{{ asset("uploads/pdf/projetrecherche/")}}{{ pr.pdf}}">
                                                <p class="icon-3d_rotation " >DOWNLOAD</p>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <hr>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>
</section><!-- End Frequently Asked Questions Section -->

<!-- Vendor JS Files -->
<script src="assets1/vendor/aos/aos.js"></script>
<script src="assets1/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>




<!-- Template Main JS File -->
<script src="assets1/js/main.js"></script>

</body>

</html>

templates/projet/sujrech.html.twig
{#<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>SUJET DE RECHERCHE</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->

    <link href="assets1/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets1/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="assets1/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">



    <!-- affichage sujet de recherche  -->

    <link href="profil/css/mdb.min.css?ver=1.2.1" rel="stylesheet">
    <link href="profil/css/main.css?ver=1.2.1" rel="stylesheet">

    <!-- Template Main CSS File -->


    <!-- Template Main CSS File -->
    <link href="assets1/css/style.css" rel="stylesheet">


</head>

<body>

<!-- ======= Header ======= -->
<header id="header" class="fixed-top ">
    <div class="container  d-flex align-items-center">

        <h1 class="logo me-auto"><a href="#faq">SUJET DE RECHERCHE</a></h1>
        <nav id="navbar" class="navbar">
            <a class="navbar-brand " href="#">
                <!--img src="{{ asset('assets/img/images.jpg') }}" width="80" height="80" alt=""-->
                <img src="{{ asset('assets/img/Logo-UIZ.jpg') }}" width="120" height="80" alt="">
            </a>
            <ul>
                <li><a class="nav-link scrollto active" href="{{ path('app_home') }}">Home</a></li>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->

    </div>
</header><!-- End Header -->
#}



<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>PROJET DE RECHERCHE</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->

    <link href="assets1/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets1/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="assets1/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">


    <!-- affichage projet de recherche  -->

    <link href="profil/css/mdb.min.css?ver=1.2.1" rel="stylesheet">
    <link href="profil/css/main.css?ver=1.2.1" rel="stylesheet">

    <!-- Template Main CSS File -->


    <!-- Template Main CSS File -->
    <link href="assets1/css/style.css" rel="stylesheet">


</head>

<body>

<!-- ======= Header ======= -->
<header  id="header" class="fixed-top ">
    <div class="container  d-flex align-items-center">

        <h1 class="logo me-auto"><a href="#faq">SUJET DE RECHERCHE</a></h1>
        <nav id="navbar" class="navbar">
            <ul >
                <form class="d-flex" method="post" action="{{ path('app_sujrech1') }}">
                    <input class="form-control me-2" type="search"  placeholder="Search" aria-label="Search" name='year'>
                    <input type="submit" class="alert-success" value="Search">
                </form>
            </ul>
            <ul>
                <li><a class="nav-link scrollto active" href="{{ path('app_home') }}">Home</a></li>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->

    </div>
</header><!-- End Header -->





<!-- ======= Frequently Asked Questions Section ======= -->
<section id="faq" class="faq section-bg">
    <div class="container" data-aos="fade-up">
        <div class="section-title">
        </div>
   {#     <div class="section-title">
            <h2>about page</h2>
            <p>
                On these pages you will find Springer’s journals, books and eBooks in all areas of Business and Management, serving researchers, professionals, lecturers and students. We publish many of the most prestigious journals in Business and Management, including a number of fully open access journals. Our book and eBook portfolio comprises major reference works, textbooks, and monographs from the world’s most distinguished authors. Well-known publications include: Springer Texts in Business and Economics, the Encyclopedia of Operations Research and Management Science, and the Journal of the Academy of Marketing Science.
            </p>
        </div>

#}
       {# {% for sr in sujrech  %}
        <div class="faq-list">
            <ul>
                <li data-aos="fade-up" data-aos-delay="100">
                    <a data-bs-toggle="collapse" class="collapse" data-bs-target="#faq-list-1">{{ sr.titre }}<i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
                    <div id="faq-list-1" class="collapse show" data-bs-parent=".faq-list">
                        <h5 >debut projet:{{ sr.datedebut |date('y/m/d     h:m') }}</h5>
                        <h5>fin projet:{{ sr.datefine|date('y/m/d     h:m') }}</h5>
                    <h4> {{ sr.master }} {{ sr.stagiaire }}</h4><hr>
                        <p>{{ sr.description }}</p>
                        <a  class="bi-file-pdf" href="{{ asset('uploads/pdf/sujetrecherche/') }}{{ sr.pdf }}">
                            <p class=" icon-holder" >voir le journal --></p>
                        </a>
                    </div>
                </li>

            </ul>
        </div>
        {% endfor %}#}


        <div style="margin-bottom: 32px" id="PR">
            <div class="row" >
                <div class="col-sm-12">
                    <div class="card-body">
                        <ul class="nav nav-tabs">
                            <li>
                               <h2> <a class="nav-link active text-uppercase h2 " aria-selected="true">SUJET DE RECHERCHE</a></h2>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>


            <div class="shadow-2-strong bg-white my- p-4">
                <div class="">
                    <div class="row">
                        <div class="col-md-12 ">

                            {% for sr in sujrech  %}
                                <div class="timeline">
                                    <div class="timeline-card timeline-card-primary card shadow-sm">
                                        <div class="card-body">
                                            <div class="h5 mb-2">{{ sr.titre }}
                                                <br>
                                                <div class="mt-2">
                                                    <span class="text-muted h6">{{ sr.encadren }} &&</span>
                                                    <span class="text-muted  h6"> {{ sr.master }} , {{ sr.stagiaire }}</span>
                                                </div>
                                            </div>
                                            <div class="text-muted text-small mb-2 "> à {{ sr.datedebut | date("20y/m/d") }}  jusqu'à  {{ sr.datefine | date("20y/m/d") }}   </div>
                                            <div>{{ sr.description}}</div>
                                            {#<span class="text-muted h6">associe à {{ sr.prAssocie }}</span>
                                            <span class="text-muted h6">{{ sr.pfe }}</span>#}
                                            <br>
                                            {#<a   class="" href="https://www.researchgate.net/publication/339129824_Machine_learning_in_Neutrosophic_Environment_A_Survey">
                                                <p class="icon-3d_rotation " >voir plus</p>
                                            </a>#}
                                            <a   class=" bi-file-pdf" href="{{ asset("uploads/pdf/sujetrecherche/")}}{{ sr.pdf}}">
                                                <p class="icon-3d_rotation " >DOWNLOAD</p>
                                            </a>

                                        </div>
                                    </div>
                                </div>
                                <hr>
                            {% endfor %}

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section><!-- End Frequently Asked Questions Section -->

<!-- Vendor JS Files -->
<script src="assets1/vendor/aos/aos.js"></script>
<script src="assets1/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>




<!-- Template Main JS File -->
<script src="assets1/js/main.js"></script>

</body>

</html>